/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    GoogleLogo: typeof import('./src/components/GoogleLogo.vue')['default']
    IconBomb: typeof import('./src/components/icons/IconBomb.vue')['default']
    IconFlag: typeof import('./src/components/icons/IconFlag.vue')['default']
    IconRoundChevronLeft: typeof import('./src/components/icons/IconRoundChevronLeft.vue')['default']
    MineBlock: typeof import('./src/components/MineBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
